### ISSUE TITLE
Cannot find type definition file for 'cypress'

### ISSUE THREAD

**Issue by mfrances17** [keycloak/keycloak-admin-ui#347]
After rebasing to latest code, I'm getting this error in VS Code:

tsconfig.json
Cannot find type definition file for 'cypress' ts [1,1]

Looking at the diff, it is most likely related to https://github.com/keycloak/keycloak-admin-ui/pull/336 when jest and cypress types were introduced at the bottom of the json file.

**Comment by mfrances17** [comment]
The issue seems to have resolved itself... i'm guessing the TS linter needed time to process it, not sure. But after 20 minutes or so, the error no longer appears.
